=begin
#Clerk Backend API

#The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).   Please see https://clerk.com/docs for more information.

The version of the OpenAPI document: v1
Contact: support@clerk.com
Generated by: https://openapi-generator.tech
Generator version: unset

=end

require 'date'
require 'time'

module ClerkHttpClient
  class CreateInvitationRequest
    # The email address the invitation will be sent to
    attr_accessor :email_address

    # Metadata that will be attached to the newly created invitation. The value of this property should be a well-formed JSON object. Once the user accepts the invitation and signs up, these metadata will end up in the user's public metadata.
    attr_accessor :public_metadata

    # Optional URL which specifies where to redirect the user once they click the invitation link. This is only required if you have implemented a [custom flow](https://clerk.com/docs/authentication/invitations#custom-flow) and you're not using Clerk Hosted Pages or Clerk Components.
    attr_accessor :redirect_url

    # Optional flag which denotes whether an email invitation should be sent to the given email address. Defaults to `true`.
    attr_accessor :notify

    # Whether an invitation should be created if there is already an existing invitation for this email address, or it's claimed by another user.
    attr_accessor :ignore_existing

    # The number of days the invitation will be valid for. By default, the invitation expires after 30 days.
    attr_accessor :expires_in_days

    # The slug of the email template to use for the invitation email. If not provided, the \"invitation\" template will be used.
    attr_accessor :template_slug

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'email_address' => :'email_address',
        :'public_metadata' => :'public_metadata',
        :'redirect_url' => :'redirect_url',
        :'notify' => :'notify',
        :'ignore_existing' => :'ignore_existing',
        :'expires_in_days' => :'expires_in_days',
        :'template_slug' => :'template_slug'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'email_address' => :'String',
        :'public_metadata' => :'Hash<String, Object>',
        :'redirect_url' => :'String',
        :'notify' => :'Boolean',
        :'ignore_existing' => :'Boolean',
        :'expires_in_days' => :'Integer',
        :'template_slug' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'notify',
        :'ignore_existing',
        :'expires_in_days',
        :'template_slug'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ClerkHttpClient::CreateInvitationRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ClerkHttpClient::CreateInvitationRequest`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'email_address')
        self.email_address = attributes[:'email_address']
      else
        self.email_address = nil
      end

      if attributes.key?(:'public_metadata')
        if (value = attributes[:'public_metadata']).is_a?(Hash)
          self.public_metadata = value
        end
      end

      if attributes.key?(:'redirect_url')
        self.redirect_url = attributes[:'redirect_url']
      end

      if attributes.key?(:'notify')
        self.notify = attributes[:'notify']
      else
        self.notify = true
      end

      if attributes.key?(:'ignore_existing')
        self.ignore_existing = attributes[:'ignore_existing']
      else
        self.ignore_existing = false
      end

      if attributes.key?(:'expires_in_days')
        self.expires_in_days = attributes[:'expires_in_days']
      end

      if attributes.key?(:'template_slug')
        self.template_slug = attributes[:'template_slug']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @email_address.nil?
        invalid_properties.push('invalid value for "email_address", email_address cannot be nil.')
      end

      if !@expires_in_days.nil? && @expires_in_days > 365
        invalid_properties.push('invalid value for "expires_in_days", must be smaller than or equal to 365.')
      end

      if !@expires_in_days.nil? && @expires_in_days < 1
        invalid_properties.push('invalid value for "expires_in_days", must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @email_address.nil?
      return false if !@expires_in_days.nil? && @expires_in_days > 365
      return false if !@expires_in_days.nil? && @expires_in_days < 1
      template_slug_validator = EnumAttributeValidator.new('String', ["invitation", "waitlist_invitation"])
      return false unless template_slug_validator.valid?(@template_slug)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] expires_in_days Value to be assigned
    def expires_in_days=(expires_in_days)
      if !expires_in_days.nil? && expires_in_days > 365
        fail ArgumentError, 'invalid value for "expires_in_days", must be smaller than or equal to 365.'
      end

      if !expires_in_days.nil? && expires_in_days < 1
        fail ArgumentError, 'invalid value for "expires_in_days", must be greater than or equal to 1.'
      end

      @expires_in_days = expires_in_days
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] template_slug Object to be assigned
    def template_slug=(template_slug)
      validator = EnumAttributeValidator.new('String', ["invitation", "waitlist_invitation"])
      unless validator.valid?(template_slug)
        fail ArgumentError, "invalid value for \"template_slug\", must be one of #{validator.allowable_values}."
      end
      @template_slug = template_slug
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          email_address == o.email_address &&
          public_metadata == o.public_metadata &&
          redirect_url == o.redirect_url &&
          notify == o.notify &&
          ignore_existing == o.ignore_existing &&
          expires_in_days == o.expires_in_days &&
          template_slug == o.template_slug
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [email_address, public_metadata, redirect_url, notify, ignore_existing, expires_in_days, template_slug].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = ClerkHttpClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

  class Model::CreateInvitationRequest < CreateInvitationRequest; end;
end
