=begin
#Clerk Backend API

#The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).   Please see https://clerk.com/docs for more information.

The version of the OpenAPI document: v1
Contact: support@clerk.com
Generated by: https://openapi-generator.tech
Generator version: 7.11.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ClerkBackend::RedirectURLsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RedirectURLsApi' do
  before do
    # run before each test
    @api_instance = ClerkBackend::RedirectURLsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RedirectURLsApi' do
    it 'should create an instance of RedirectURLsApi' do
      expect(@api_instance).to be_instance_of(ClerkBackend::RedirectURLsApi)
    end
  end

  # unit tests for create_redirect_url
  # Create a redirect URL
  # Create a redirect URL
  # @param [Hash] opts the optional parameters
  # @option opts [CreateRedirectURLRequest] :create_redirect_url_request 
  # @return [RedirectURL]
  describe 'create_redirect_url test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_redirect_url
  # Delete a redirect URL
  # Remove the selected redirect URL from the whitelist of the instance
  # @param id The ID of the redirect URL
  # @param [Hash] opts the optional parameters
  # @return [DeletedObject]
  describe 'delete_redirect_url test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_redirect_url
  # Retrieve a redirect URL
  # Retrieve the details of the redirect URL with the given ID
  # @param id The ID of the redirect URL
  # @param [Hash] opts the optional parameters
  # @return [RedirectURL]
  describe 'get_redirect_url test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_redirect_urls
  # List all redirect URLs
  # Lists all whitelisted redirect_urls for the instance
  # @param [Hash] opts the optional parameters
  # @return [Array<RedirectURL>]
  describe 'list_redirect_urls test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
