=begin
#Clerk Backend API

#The Clerk REST Backend API, meant to be accessed by backend servers.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/versioning/available-versions).  Please see https://clerk.com/docs for more information.

The version of the OpenAPI document: 2021-02-05
Contact: support@clerk.com
Generated by: https://openapi-generator.tech
Generator version: unset

=end

require 'spec_helper'
require 'json'

# Unit tests for ClerkHttpClient::MachinesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MachinesApi' do
  before do
    # run before each test
    @api_instance = ClerkHttpClient::MachinesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MachinesApi' do
    it 'should create an instance of MachinesApi' do
      expect(@api_instance).to be_instance_of(ClerkHttpClient::MachinesApi)
    end
  end

  # unit tests for create_machine
  # Create a machine
  # Creates a new machine.
  # @param [Hash] opts the optional parameters
  # @option opts [CreateMachineRequest] :create_machine_request 
  # @return [Machine]
  describe 'create_machine test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_machine_scope
  # Create a machine scope
  # Creates a new machine scope, allowing the specified machine to access another machine. Maximum of 25 scopes per machine.
  # @param machine_id The ID of the machine that will have access to another machine
  # @param [Hash] opts the optional parameters
  # @option opts [CreateMachineScopeRequest] :create_machine_scope_request 
  # @return [MachineScope]
  describe 'create_machine_scope test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_machine
  # Delete a machine
  # Deletes a machine.
  # @param machine_id The ID of the machine to delete
  # @param [Hash] opts the optional parameters
  # @return [DeleteMachine200Response]
  describe 'delete_machine test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_machine_scope
  # Delete a machine scope
  # Deletes a machine scope, removing access from one machine to another.
  # @param machine_id The ID of the machine that has access to another machine
  # @param other_machine_id The ID of the machine that is being accessed
  # @param [Hash] opts the optional parameters
  # @return [DeleteMachineScope200Response]
  describe 'delete_machine_scope test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_machine
  # Retrieve a machine
  # Returns the details of a machine.
  # @param machine_id The ID of the machine to retrieve
  # @param [Hash] opts the optional parameters
  # @return [Machine]
  describe 'get_machine test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_machines
  # Get a list of machines for an instance
  # This request returns the list of machines for an instance. The machines are ordered by descending creation date (i.e. most recent machines will be returned first)
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Applies a limit to the number of results returned. Can be used for paginating the results together with &#x60;offset&#x60;.
  # @option opts [Integer] :offset Skip the first &#x60;offset&#x60; results when paginating. Needs to be an integer greater or equal to zero. To be used in conjunction with &#x60;limit&#x60;.
  # @option opts [String] :query Returns machines with ID or name that match the given query. Uses exact match for machine ID and partial match for name.
  # @return [ListMachines200Response]
  describe 'list_machines test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_machine
  # Update a machine
  # Updates an existing machine. Only the provided fields will be updated.
  # @param machine_id The ID of the machine to update
  # @param [Hash] opts the optional parameters
  # @option opts [UpdateMachineRequest] :update_machine_request 
  # @return [Machine]
  describe 'update_machine test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
