# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module ClerkSDKBackend
  module Operations
  

    class DeleteOAuthApplicationRequest < ::ClerkSDKBackend::Utils::FieldAugmented
      extend T::Sig

      # The ID of the OAuth application to delete
      field :oauth_application_id, ::String, { 'path_param': { 'field_name': 'oauth_application_id', 'style': 'simple', 'explode': false } }


      sig { params(oauth_application_id: ::String).void }
      def initialize(oauth_application_id: nil)
        @oauth_application_id = oauth_application_id
      end
    end
  end
end
