# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module ClerkSDKBackend
  module Operations
  

    class DeleteAllowlistIdentifierRequest < ::ClerkSDKBackend::Utils::FieldAugmented
      extend T::Sig

      # The ID of the identifier to delete from the allow-list
      field :identifier_id, ::String, { 'path_param': { 'field_name': 'identifier_id', 'style': 'simple', 'explode': false } }


      sig { params(identifier_id: ::String).void }
      def initialize(identifier_id: nil)
        @identifier_id = identifier_id
      end
    end
  end
end
