# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module ClerkSDKBackend
  module Operations
  

    class GetClientRequest < ::ClerkSDKBackend::Utils::FieldAugmented
      extend T::Sig

      # Client ID.
      field :client_id, ::String, { 'path_param': { 'field_name': 'client_id', 'style': 'simple', 'explode': false } }


      sig { params(client_id: ::String).void }
      def initialize(client_id: nil)
        @client_id = client_id
      end
    end
  end
end
