# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module ClerkSDKBackend
  module Operations
  

    class GetPhoneNumberRequest < ::ClerkSDKBackend::Utils::FieldAugmented
      extend T::Sig

      # The ID of the phone number to retrieve
      field :phone_number_id, ::String, { 'path_param': { 'field_name': 'phone_number_id', 'style': 'simple', 'explode': false } }


      sig { params(phone_number_id: ::String).void }
      def initialize(phone_number_id: nil)
        @phone_number_id = phone_number_id
      end
    end
  end
end
