# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module ClerkSDKBackend
  module Operations
  

    class LockUserRequest < ::ClerkSDKBackend::Utils::FieldAugmented
      extend T::Sig

      # The ID of the user to lock
      field :user_id, ::String, { 'path_param': { 'field_name': 'user_id', 'style': 'simple', 'explode': false } }


      sig { params(user_id: ::String).void }
      def initialize(user_id: nil)
        @user_id = user_id
      end
    end
  end
end
