# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module ClerkSDKBackend
  module Operations
  

    class SetUserProfileImageRequestBody < ::ClerkSDKBackend::Utils::FieldAugmented
      extend T::Sig


      field :file, T.nilable(::ClerkSDKBackend::Operations::File), { 'multipart_form': { 'file': true } }


      sig { params(file: T.nilable(::ClerkSDKBackend::Operations::File)).void }
      def initialize(file: nil)
        @file = file
      end
    end
  end
end
