# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module ClerkSDKBackend
  module Operations
  

    class UpdateJWTTemplateRequest < ::ClerkSDKBackend::Utils::FieldAugmented
      extend T::Sig


      field :request_body, ::ClerkSDKBackend::Operations::UpdateJWTTemplateRequestBody, { 'request': { 'media_type': 'application/json' } }
      # The ID of the JWT template to update
      field :template_id, ::String, { 'path_param': { 'field_name': 'template_id', 'style': 'simple', 'explode': false } }


      sig { params(request_body: ::ClerkSDKBackend::Operations::UpdateJWTTemplateRequestBody, template_id: ::String).void }
      def initialize(request_body: nil, template_id: nil)
        @request_body = request_body
        @template_id = template_id
      end
    end
  end
end
