# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module ClerkSDKBackend
  module Operations
  

    class UpdateOrganizationDomainRequestBody < ::ClerkSDKBackend::Utils::FieldAugmented
      extend T::Sig

      # The enrollment_mode for the new domain. This can be `automatic_invitation`, `automatic_suggestion` or `manual_invitation`
      field :enrollment_mode, T.nilable(::String), { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('enrollment_mode') } }
      # The status of the domain's verification
      field :verified, T.nilable(T::Boolean), { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('verified') } }


      sig { params(enrollment_mode: T.nilable(::String), verified: T.nilable(T::Boolean)).void }
      def initialize(enrollment_mode: nil, verified: nil)
        @enrollment_mode = enrollment_mode
        @verified = verified
      end
    end
  end
end
