# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module ClerkSDKBackend
  module Operations
  
    # Metadata saved on the user, that can be updated from both the Frontend and Backend APIs.
    # Note: Since this data can be modified from the frontend, it is not guaranteed to be safe.
    class UpdateUserUnsafeMetadata < ::ClerkSDKBackend::Utils::FieldAugmented
      extend T::Sig



      
      def initialize; end
    end
  end
end
