# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module ClerkSDKBackend
  module Operations
  

    class UpdateSignUpRequestBody < ::ClerkSDKBackend::Utils::FieldAugmented
      extend T::Sig

      # The ID of the guest attempting to sign up as used in your external systems or your previous authentication solution.
      # This will be copied to the resulting user when the sign-up is completed.
      field :external_id, T.nilable(::String), { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('external_id') } }


      sig { params(external_id: T.nilable(::String)).void }
      def initialize(external_id: nil)
        @external_id = external_id
      end
    end
  end
end
