# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module ClerkSDKBackend
  module Operations
  

    class UpdateOrganizationMembershipMetadataRequest < ::ClerkSDKBackend::Utils::FieldAugmented
      extend T::Sig

      # The ID of the organization the membership belongs to
      field :organization_id, ::String, { 'path_param': { 'field_name': 'organization_id', 'style': 'simple', 'explode': false } }

      field :request_body, ::ClerkSDKBackend::Operations::UpdateOrganizationMembershipMetadataRequestBody, { 'request': { 'media_type': 'application/json' } }
      # The ID of the user that this membership belongs to
      field :user_id, ::String, { 'path_param': { 'field_name': 'user_id', 'style': 'simple', 'explode': false } }


      sig { params(organization_id: ::String, request_body: ::ClerkSDKBackend::Operations::UpdateOrganizationMembershipMetadataRequestBody, user_id: ::String).void }
      def initialize(organization_id: nil, request_body: nil, user_id: nil)
        @organization_id = organization_id
        @request_body = request_body
        @user_id = user_id
      end
    end
  end
end
