# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module ClerkSDKBackend
  module Operations
  

    class UsersGetOrganizationMembershipsRequest < ::ClerkSDKBackend::Utils::FieldAugmented
      extend T::Sig

      # The ID of the user whose organization memberships we want to retrieve
      field :user_id, ::String, { 'path_param': { 'field_name': 'user_id', 'style': 'simple', 'explode': false } }
      # Applies a limit to the number of results returned.
      # Can be used for paginating the results together with `offset`.
      field :limit, T.nilable(::Float), { 'query_param': { 'field_name': 'limit', 'style': 'form', 'explode': true } }
      # Skip the first `offset` results when paginating.
      # Needs to be an integer greater or equal to zero.
      # To be used in conjunction with `limit`.
      field :offset, T.nilable(::Float), { 'query_param': { 'field_name': 'offset', 'style': 'form', 'explode': true } }


      sig { params(user_id: ::String, limit: T.nilable(::Float), offset: T.nilable(::Float)).void }
      def initialize(user_id: nil, limit: nil, offset: nil)
        @user_id = user_id
        @limit = limit
        @offset = offset
      end
    end
  end
end
