# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module ClerkSDKBackend
  module Shared
  
    # Success
    class ActorToken < ::ClerkSDKBackend::Utils::FieldAugmented
      extend T::Sig


      field :actor, ::ClerkSDKBackend::Shared::ActorTokenActor, { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('actor') } }
      # Unix timestamp of creation.
      # 
      field :created_at, ::Integer, { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('created_at') } }

      field :id, ::String, { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('id') } }

      field :object, ::ClerkSDKBackend::Shared::ActorTokenObject, { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('object'), 'decoder': Utils.enum_from_string(::ClerkSDKBackend::Shared::ActorTokenObject, false) } }

      field :status, ::ClerkSDKBackend::Shared::ActorTokenStatus, { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('status'), 'decoder': Utils.enum_from_string(::ClerkSDKBackend::Shared::ActorTokenStatus, false) } }
      # Unix timestamp of last update.
      # 
      field :updated_at, ::Integer, { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('updated_at') } }

      field :user_id, ::String, { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('user_id') } }

      field :token, T.nilable(::String), { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('token') } }

      field :url, T.nilable(::String), { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('url') } }


      sig { params(actor: ::ClerkSDKBackend::Shared::ActorTokenActor, created_at: ::Integer, id: ::String, object: ::ClerkSDKBackend::Shared::ActorTokenObject, status: ::ClerkSDKBackend::Shared::ActorTokenStatus, updated_at: ::Integer, user_id: ::String, token: T.nilable(::String), url: T.nilable(::String)).void }
      def initialize(actor: nil, created_at: nil, id: nil, object: nil, status: nil, updated_at: nil, user_id: nil, token: nil, url: nil)
        @actor = actor
        @created_at = created_at
        @id = id
        @object = object
        @status = status
        @updated_at = updated_at
        @user_id = user_id
        @token = token
        @url = url
      end
    end
  end
end
