# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module ClerkSDKBackend
  module Shared
  
    # Success
    class Client < ::ClerkSDKBackend::Utils::FieldAugmented
      extend T::Sig

      # Unix timestamp of creation.
      # 
      field :created_at, ::Integer, { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('created_at') } }
      # String representing the identifier of the session.
      # 
      field :id, ::String, { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('id') } }
      # Last active session_id.
      # 
      field :last_active_session_id, ::String, { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('last_active_session_id') } }
      # String representing the object's type. Objects of the same type share the same value.
      # 
      field :object, ::ClerkSDKBackend::Shared::Object, { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('object'), 'decoder': Utils.enum_from_string(::ClerkSDKBackend::Shared::Object, false) } }

      field :session_ids, T::Array[::String], { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('session_ids') } }

      field :sessions, T::Array[::ClerkSDKBackend::Shared::Session], { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('sessions') } }

      field :sign_in_id, ::String, { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('sign_in_id') } }

      field :sign_up_id, ::String, { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('sign_up_id') } }
      # Unix timestamp of last update.
      # 
      field :updated_at, ::Integer, { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('updated_at') } }


      sig { params(created_at: ::Integer, id: ::String, last_active_session_id: ::String, object: ::ClerkSDKBackend::Shared::Object, session_ids: T::Array[::String], sessions: T::Array[::ClerkSDKBackend::Shared::Session], sign_in_id: ::String, sign_up_id: ::String, updated_at: ::Integer).void }
      def initialize(created_at: nil, id: nil, last_active_session_id: nil, object: nil, session_ids: nil, sessions: nil, sign_in_id: nil, sign_up_id: nil, updated_at: nil)
        @created_at = created_at
        @id = id
        @last_active_session_id = last_active_session_id
        @object = object
        @session_ids = session_ids
        @sessions = sessions
        @sign_in_id = sign_in_id
        @sign_up_id = sign_up_id
        @updated_at = updated_at
      end
    end
  end
end
