# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module ClerkSDKBackend
  module Shared
  

    class DomainObject < T::Enum
      enums do
        DOMAIN = new('domain')
      end
    end
  end
end
