# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module ClerkSDKBackend
  module Shared
  
    # EmailAddressObject - String representing the object's type. Objects of the same type share the same value.
    # 
    class EmailAddressObject < T::Enum
      enums do
        EMAIL_ADDRESS = new('email_address')
      end
    end
  end
end
