# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module ClerkSDKBackend
  module Shared
  
    # Success
    class EmailAddress < ::ClerkSDKBackend::Utils::FieldAugmented
      extend T::Sig

      # Unix timestamp of creation
      # 
      field :created_at, ::Integer, { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('created_at') } }

      field :email_address, ::String, { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('email_address') } }

      field :linked_to, T::Array[::ClerkSDKBackend::Shared::IdentificationLink], { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('linked_to') } }
      # String representing the object's type. Objects of the same type share the same value.
      # 
      field :object, ::ClerkSDKBackend::Shared::EmailAddressObject, { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('object'), 'decoder': Utils.enum_from_string(::ClerkSDKBackend::Shared::EmailAddressObject, false) } }

      field :reserved, T::Boolean, { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('reserved') } }
      # Unix timestamp of creation
      # 
      field :updated_at, ::Integer, { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('updated_at') } }

      field :verification, ::Object, { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('verification') } }

      field :id, T.nilable(::String), { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('id') } }


      sig { params(created_at: ::Integer, email_address: ::String, linked_to: T::Array[::ClerkSDKBackend::Shared::IdentificationLink], object: ::ClerkSDKBackend::Shared::EmailAddressObject, reserved: T::Boolean, updated_at: ::Integer, verification: ::Object, id: T.nilable(::String)).void }
      def initialize(created_at: nil, email_address: nil, linked_to: nil, object: nil, reserved: nil, updated_at: nil, verification: nil, id: nil)
        @created_at = created_at
        @email_address = email_address
        @linked_to = linked_to
        @object = object
        @reserved = reserved
        @updated_at = updated_at
        @verification = verification
        @id = id
      end
    end
  end
end
