# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module ClerkSDKBackend
  module Shared
  
    # InstanceRestrictionsObject - String representing the object's type. Objects of the same type share the same value.
    class InstanceRestrictionsObject < T::Enum
      enums do
        INSTANCE_RESTRICTIONS = new('instance_restrictions')
      end
    end
  end
end
