# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module ClerkSDKBackend
  module Shared
  

    class LatestActivity < ::ClerkSDKBackend::Utils::FieldAugmented
      extend T::Sig


      field :id, ::String, { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('id') } }

      field :object, ::String, { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('object') } }

      field :browser_name, T.nilable(::String), { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('browser_name') } }

      field :browser_version, T.nilable(::String), { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('browser_version') } }

      field :city, T.nilable(::String), { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('city') } }

      field :country, T.nilable(::String), { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('country') } }

      field :device_type, T.nilable(::String), { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('device_type') } }

      field :ip_address, T.nilable(::String), { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('ip_address') } }

      field :is_mobile, T.nilable(T::Boolean), { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('is_mobile') } }


      sig { params(id: ::String, object: ::String, browser_name: T.nilable(::String), browser_version: T.nilable(::String), city: T.nilable(::String), country: T.nilable(::String), device_type: T.nilable(::String), ip_address: T.nilable(::String), is_mobile: T.nilable(T::Boolean)).void }
      def initialize(id: nil, object: nil, browser_name: nil, browser_version: nil, city: nil, country: nil, device_type: nil, ip_address: nil, is_mobile: nil)
        @id = id
        @object = object
        @browser_name = browser_name
        @browser_version = browser_version
        @city = city
        @country = country
        @device_type = device_type
        @ip_address = ip_address
        @is_mobile = is_mobile
      end
    end
  end
end
