# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module ClerkSDKBackend
  module Shared
  
    # OrganizationSettingsObject - String representing the object's type. Objects of the same type share the same value.
    class OrganizationSettingsObject < T::Enum
      enums do
        ORGANIZATION_SETTINGS = new('organization_settings')
      end
    end
  end
end
