# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module ClerkSDKBackend
  module Shared
  
    # OrganizationInvitationWithPublicOrganizationDataObject - String representing the object's type. Objects of the same type share the same value.
    # 
    class OrganizationInvitationWithPublicOrganizationDataObject < T::Enum
      enums do
        ORGANIZATION_INVITATION = new('organization_invitation')
      end
    end
  end
end
