# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module ClerkSDKBackend
  module Shared
  
    # OrganizationDomainStatus - Status of the verification. It can be `unverified` or `verified`
    class OrganizationDomainStatus < T::Enum
      enums do
        UNVERIFIED = new('unverified')
        VERIFIED = new('verified')
      end
    end
  end
end
