# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module ClerkSDKBackend
  module Shared
  
    # OrganizationDomainObject - String representing the object's type. Objects of the same type share the same value. Always `organization_domain`
    # 
    class OrganizationDomainObject < T::Enum
      enums do
        ORGANIZATION_DOMAIN = new('organization_domain')
      end
    end
  end
end
