# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module ClerkSDKBackend
  module Shared
  
    # PhoneNumberObject - String representing the object's type. Objects of the same type share the same value.
    # 
    class PhoneNumberObject < T::Enum
      enums do
        PHONE_NUMBER = new('phone_number')
      end
    end
  end
end
