# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module ClerkSDKBackend
  module Shared
  

    class RedirectURLObject < T::Enum
      enums do
        REDIRECT_URL = new('redirect_url')
      end
    end
  end
end
