# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module ClerkSDKBackend
  module Shared
  
    # SAMLAccountObject - String representing the object's type. Objects of the same type share the same value.
    # 
    class SAMLAccountObject < T::Enum
      enums do
        SAML_ACCOUNT = new('saml_account')
      end
    end
  end
end
