# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module ClerkSDKBackend
  module Shared
  
    # SchemasPasskeyObject - String representing the object's type. Objects of the same type share the same value.
    # 
    class SchemasPasskeyObject < T::Enum
      enums do
        PASSKEY = new('passkey')
      end
    end
  end
end
