# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module ClerkSDKBackend
  module Shared
  
    # SessionObject - String representing the object's type. Objects of the same type share the same value.
    # 
    class SessionObject < T::Enum
      enums do
        SESSION = new('session')
      end
    end
  end
end
