# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module ClerkSDKBackend
  module Shared
  
    # Success
    class SignUp < ::ClerkSDKBackend::Utils::FieldAugmented
      extend T::Sig


      field :abandon_at, ::Integer, { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('abandon_at') } }

      field :custom_action, T::Boolean, { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('custom_action') } }

      field :id, ::String, { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('id') } }

      field :object, ::ClerkSDKBackend::Shared::SignUpObject, { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('object'), 'decoder': Utils.enum_from_string(::ClerkSDKBackend::Shared::SignUpObject, false) } }

      field :password_enabled, T::Boolean, { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('password_enabled') } }

      field :status, ::ClerkSDKBackend::Shared::SignUpStatus, { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('status'), 'decoder': Utils.enum_from_string(::ClerkSDKBackend::Shared::SignUpStatus, false) } }

      field :created_session_id, T.nilable(::String), { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('created_session_id') } }

      field :created_user_id, T.nilable(::String), { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('created_user_id') } }

      field :email_address, T.nilable(::String), { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('email_address') } }

      field :external_account, T.nilable(::ClerkSDKBackend::Shared::ExternalAccount), { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('external_account') } }

      field :external_id, T.nilable(::String), { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('external_id') } }

      field :first_name, T.nilable(::String), { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('first_name') } }

      field :last_name, T.nilable(::String), { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('last_name') } }

      field :missing_fields, T.nilable(T::Array[::String]), { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('missing_fields') } }

      field :optional_fields, T.nilable(T::Array[::String]), { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('optional_fields') } }

      field :phone_number, T.nilable(::String), { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('phone_number') } }

      field :public_metadata, T.nilable(::ClerkSDKBackend::Shared::SignUpPublicMetadata), { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('public_metadata') } }

      field :required_fields, T.nilable(T::Array[::String]), { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('required_fields') } }

      field :unsafe_metadata, T.nilable(::ClerkSDKBackend::Shared::SignUpUnsafeMetadata), { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('unsafe_metadata') } }

      field :unverified_fields, T.nilable(T::Array[::String]), { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('unverified_fields') } }

      field :username, T.nilable(::String), { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('username') } }

      field :verifications, T.nilable(::ClerkSDKBackend::Shared::Verifications), { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('verifications') } }

      field :web3_wallet, T.nilable(::String), { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('web3_wallet') } }


      sig { params(abandon_at: ::Integer, custom_action: T::Boolean, id: ::String, object: ::ClerkSDKBackend::Shared::SignUpObject, password_enabled: T::Boolean, status: ::ClerkSDKBackend::Shared::SignUpStatus, created_session_id: T.nilable(::String), created_user_id: T.nilable(::String), email_address: T.nilable(::String), external_account: T.nilable(::ClerkSDKBackend::Shared::ExternalAccount), external_id: T.nilable(::String), first_name: T.nilable(::String), last_name: T.nilable(::String), missing_fields: T.nilable(T::Array[::String]), optional_fields: T.nilable(T::Array[::String]), phone_number: T.nilable(::String), public_metadata: T.nilable(::ClerkSDKBackend::Shared::SignUpPublicMetadata), required_fields: T.nilable(T::Array[::String]), unsafe_metadata: T.nilable(::ClerkSDKBackend::Shared::SignUpUnsafeMetadata), unverified_fields: T.nilable(T::Array[::String]), username: T.nilable(::String), verifications: T.nilable(::ClerkSDKBackend::Shared::Verifications), web3_wallet: T.nilable(::String)).void }
      def initialize(abandon_at: nil, custom_action: nil, id: nil, object: nil, password_enabled: nil, status: nil, created_session_id: nil, created_user_id: nil, email_address: nil, external_account: nil, external_id: nil, first_name: nil, last_name: nil, missing_fields: nil, optional_fields: nil, phone_number: nil, public_metadata: nil, required_fields: nil, unsafe_metadata: nil, unverified_fields: nil, username: nil, verifications: nil, web3_wallet: nil)
        @abandon_at = abandon_at
        @custom_action = custom_action
        @id = id
        @object = object
        @password_enabled = password_enabled
        @status = status
        @created_session_id = created_session_id
        @created_user_id = created_user_id
        @email_address = email_address
        @external_account = external_account
        @external_id = external_id
        @first_name = first_name
        @last_name = last_name
        @missing_fields = missing_fields
        @optional_fields = optional_fields
        @phone_number = phone_number
        @public_metadata = public_metadata
        @required_fields = required_fields
        @unsafe_metadata = unsafe_metadata
        @unverified_fields = unverified_fields
        @username = username
        @verifications = verifications
        @web3_wallet = web3_wallet
      end
    end
  end
end
