# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module ClerkSDKBackend
  module Shared
  

    class SignUpStatus < T::Enum
      enums do
        MISSING_REQUIREMENTS = new('missing_requirements')
        COMPLETE = new('complete')
        ABANDONED = new('abandoned')
      end
    end
  end
end
