# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module ClerkSDKBackend
  module Shared
  
    # Get the JSON Web Key Set
    class WellKnownJWKS < ::ClerkSDKBackend::Utils::FieldAugmented
      extend T::Sig


      field :keys, T.nilable(T::Array[::ClerkSDKBackend::Shared::Keys]), { 'format_json': { 'letter_case': ::ClerkSDKBackend::Utils.field_name('keys') } }


      sig { params(keys: T.nilable(T::Array[::ClerkSDKBackend::Shared::Keys])).void }
      def initialize(keys: nil)
        @keys = keys
      end
    end
  end
end
