language: ruby
cache: bundler
rvm:
  - 2.7
  - 3.0
  - 3.1
script:
  - bundle install --path vendor/bundle
  - bundle exec rspec
  - gem build clerk-backend.gemspec
  - gem install ./clerk-backend-1.0.0.gem
