name: Generate Ruby Backend SDK
on:
  workflow_dispatch:
    inputs:
      id:
        type: string
        description: "The ID of the pull request"
        required: false
      url:
        type: string
        description: "The URL of the pull request"
        default: "https://github.com/clerk/openapi-specs"
        required: false
      title:
        type: string
        description: "The title of the pull request"
        default: "Generate Ruby Backend SDK"
        required: false
      description:
        type: string
        description: "The description of the pull request"
        default: "Generated independently of an OpenAPI spec change"
        required: false

jobs:
  generate-sdk:
    runs-on: ubuntu-latest
    name: Generate
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Move root to ./out
        run: |
          rm -rf ./out
          mkdir ./out
          shopt -s extglob
          shopt -s dotglob
          mv !(out) ./out

      - name: Generate new client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: ruby
          command-args: -o out --api-name-suffix=' '
          config-file: out/sdk-generator-config.json
          openapi-file: out/resources/oas/bapi-2024-10-01.yml
          # openapi-url: https://raw.githubusercontent.com/clerk/openapi-specs/refs/heads/main/bapi/2024-10-01.yml
          template-dir: out/resources/templates

      - name: Move generated files to root
        run: |
          shopt -s extglob
          shopt -s dotglob
          mv -fv ./out/* .
          rm -rv ./out
          ls -la .

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        # Skips local testing with `act`
        if: ${{ github.actor != 'nektos/act' }}
        with:
          title: ${{ inputs.title }}
          body: "${{ inputs.description }}\n\n${{ inputs.url }}"
          branch: "generate-sdk"
          commit-message: "Generate Ruby Backend SDK"
          branch-suffix: "timestamp"
          assignees: "tmilewski"
          reviewers: "tmilewski"
